#!/usr/bin/env python3

import sys
import subprocess
import env

host = env.VPS_HOST
allowed_users = env.VPS_ALLOWED_USERS
default_user = env.VPS_DEFAULT_USER

user = sys.argv[1] if len(sys.argv) > 1 else default_user

if not user in allowed_users:
  print('Wrong username')
  sys.exit()

command = f'ssh {user}@{host}'

try:
  subprocess.run(command, shell=True)
except KeyboardInterrupt:
  sys.exit()

